### ISSUE TITLE
.

### ISSUE THREAD

**Issue by wtyCSDN** [sixgad/sixgad.github.io#1]

**Comment by sixgad** [comment]
什么问题呢

**Comment by sixgad** [comment]
> 大佬，能不能向您请教个问题啊？

什么问题呢？

**Comment by wtyCSDN** [comment]
我按照您之前的文章通过导webpack的方式得到dy的captchabody加密结果，但是拿去验证都是错的，我感觉和我补的环境或者是我加密的轨迹那部分的参数格式是错的，能不能麻烦大佬指点一下？

**Comment by sixgad** [comment]
> 我按照您之前的文章通过导webpack的方式得到dy的captchabody加密结果，但是拿去验证都是错的，我感觉和我补的环境或者是我加密的轨迹那部分的参数格式是错的，能不能麻烦大佬指点一下？

那篇文章已经挺久了，dy后面也更新了吧，没啥参考价值了。。。

**Comment by wtyCSDN** [comment]
大佬是否方便发一份之前的我研究下呢，学习一下思路
